### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shanow7** [VainlyStrain/Vaile#5]
Traceback (most recent call last):
  File "Vaile.py", line 29, in <module>
    import core.methods.select as select
  File "/home/user/Desktop/vaile/core/methods/select.py", line 26, in <module>
    import texttable as table
ModuleNotFoundError: No module named 'texttable'

can you help?

**Comment by VainlyStrain** [comment]
Did you install the python dependencies? (requirements.txt)

If yes, were you using pip3?

**Comment by shanow7** [comment]
yes

**Comment by VainlyStrain** [comment]
Does the pip installation pass without errors? Can you post the logs? Which OS/distro are you using?

**Comment by shanow7** [comment]
Requirement already satisfied: soupsieve>=1.2 in /usr/lib/python3/dist-packages (from beautifulsoup4->bs4->-r requirements.txt (line 10)) (1.9.3)
┌─[user@parrot]─[~/Desktop/vaile]
└──╼ $sudo python3 Vaile.py
Traceback (most recent call last):
  File "Vaile.py", line 29, in <module>
    import core.methods.select as select
  File "/home/user/Desktop/vaile/core/methods/select.py", line 26, in <module>
    import texttable as table
ModuleNotFoundError: No module named 'texttable'

I'm using parrot

**Comment by VainlyStrain** [comment]
Did you try using a specific version of pip3 (eg pip3.5 )? Which version of python do you have? Have you checked if the texttable script is in /usr/lib*/python3?

**Comment by shanow7** [comment]
python --version
Python 3.7.4+
┌─[user@parrot]─[~/Desktop/vaile]
└──╼ $pip --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)

**Comment by VainlyStrain** [comment]
Try cloning texttable from git and installing it from source. If the issue persists, move the files into core/lib and edit the import in select.py to point to the installation folder.

**Comment by VainlyStrain** [comment]
closing the issue for now
