### ISSUE TITLE
vaile

### ISSUE THREAD

**Issue by shanow7** [VainlyStrain/Vaile#6]
maybe you have a video on YB how to use Vaile or commands to load modules and how to use them?

**Comment by VainlyStrain** [comment]
A first look of the framework is provided here: https://youtu.be/jKoraki1qJM
For more advanced commands (like sessions), you can consult the help menu using ? <command>.
When attacking with a module, it will lead you step for step through the configuration (pre-defined configuration using set is also coming), and do the rest for you. Cheers

**Comment by shanow7** [comment]
I try to use module passive-all but I've message 
![image](https://user-images.githubusercontent.com/37192410/71556932-ed8cfb80-2a3e-11ea-9919-489583f059e8.png)

**Comment by VainlyStrain** [comment]
Issue fixed in latest commit. Thanks for reporting!
