### ISSUE TITLE
Unable to install Requirements on Kali

### ISSUE THREAD

**Issue by MiTeePingWin** [VainlyStrain/Vaile#7]
Unable to install on Kali, I'm getting the same errors posted on the TIDoS-Framework project issues:
https://github.com/0xInfection/TIDoS-Framework/issues/80
https://github.com/0xInfection/TIDoS-Framework/issues/85

I wasn't able to install libmysqlclient-dev
Installing libmariadbclient18 says it's not found, but to install libmariadb3

`Package libmariadbclient18 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libmariadb3

E: Package 'libmariadbclient18' has no installation `candidate``

Running on Kali, getting the error when running:
pip3 install -r requirements.txt

`Collecting` mysqlclient (from mysql->-r requirements.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/d0/97/7326248ac8d5049968bf4ec708a5d3d4806e412a42e74160d7f266a3e03a/mysqlclient-1.4.6.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vfyl70zv/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-vfyl70zv/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-vfyl70zv/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in `/tmp/pip-install-vfyl70zv/mysqlclient/`

**Comment by MiTeePingWin** [comment]
Nevermind! I fixed this by performing:

sudo apt install libmysqlclient-dev default-libmysqlclient-dev

See https://github.com/0xInfection/TIDoS-Framework/issues/78

**Comment by VainlyStrain** [comment]
Glad you were able to resolve the issue! Have had the same problem on an Ubuntu Test VM
